apiVersion: integration/v1
kind: Trigger
name: dynatrace-trigger-event-fired
version: 1
summary: Dynatrace event fired
description: |
  This trigger handles Dynatrace Problem Notifications sent to Relay.

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/dynatrace-trigger-event-fired
